#requires -Version 5.1
<#
.SYNOPSIS
  Generate per-runtime agent config (.claude, .cursor, AGENTS.md) from .agents/ — the single
  source of truth. Run after editing anything under .agents/. Idempotent.

.DESCRIPTION
  .agents/ holds the canonical rules + board identity for this repo. Each agent runtime wants
  the same rules in its own format; hand-syncing N directories drifts. So we GENERATE them:

    .agents/rules/*.md  +  .agents/board.json
        │
        ├─> AGENTS.md                          (cross-tool standard: Cursor, others read it)
        ├─> .cursor/rules/00-akira-agents.mdc  (Cursor, alwaysApply — only if AKIRA_CURSOR=1)
        ├─> .claude/CLAUDE.agents.md           (rules block Claude reads)
        └─> .claude/settings.json              (merge a SessionStart hook: `akira-board sync`)

  Generated files carry a "DO NOT EDIT" header and are checksummed into .agents/agents.lock.

.PARAMETER Check
  Don't write — verify generated outputs still match the lock (CI / pre-commit). Exits 1 on
  drift (a generated file was hand-edited or is stale), 0 if clean.
#>
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = "Stop"
$agentsDir = $PSScriptRoot
$repoRoot  = Split-Path -Parent $agentsDir
$rulesDir  = Join-Path $agentsDir "rules"
$lockPath  = Join-Path $agentsDir "agents.lock"
$marker    = "akira-board"        # identifies OUR managed Claude hook (substring of BOTH the repo-relative and PATH-shim $hookCmd forms)

# Cursor is OPT-IN (AKIRA_CURSOR=1), matching the rest of the stack — the subscription was cancelled
# 2026-07-28 and the privileged sensitive-ip lane is host Claude only. Off, we neither emit nor
# checksum the .cursor artifacts, AND we retire any left by an earlier generation: stale alwaysApply
# rules and a dead `akira-mcp-board` MCP entry in ~35 repos are config that looks live but isn't.
# Note this reads the process env, not akira's .env — a repo running .agents/generate.ps1 standalone
# has no .env loaded, so the fail-safe default (disabled) is the one that applies there. Correct: a
# repo should not sprout Cursor config just because it was generated outside the akira stack.
$cursorEnabled = $env:AKIRA_CURSOR -match '^(1|true|yes|on)$'

$WARN = "GENERATED by .agents/generate.ps1 from .agents/ — DO NOT EDIT. Edit .agents/rules/*.md and re-run."

# --- gather source -----------------------------------------------------------------------
if (-not (Test-Path $rulesDir)) { throw "No .agents/rules dir at $rulesDir" }
$ruleFiles = Get-ChildItem $rulesDir -Filter *.md | Sort-Object Name
if (-not $ruleFiles) { throw "No rule files in $rulesDir" }

# A rule file MAY carry leading frontmatter with an inline `paths:` JSON array, e.g.
#     ---
#     paths: ["deploy/**", "**/secrets/**"]
#     ---
# Such a file is emitted as its OWN path-scoped Claude rule (.claude/rules/akira-<name>.md) that
# Claude loads only when working under a matching path — keeping large, situational operational
# guidance (fleet access, one-off hardware boxes) out of every session's always-loaded context.
# Files with no frontmatter concatenate into the always-loaded rules block, as before. AGENTS.md
# and the Cursor .mdc always include EVERYTHING (their scoping model differs); this split is
# Claude-specific. A `paths:` that fails to parse falls back to always-loaded (fail-safe: worst
# case the guidance stays always-on, never silently dropped).
function Split-RuleFrontmatter([string]$raw) {
  if ($raw -match "(?s)^﻿?---\r?\n(.*?)\r?\n---\r?\n(.*)$") {
    $fm = $Matches[1]; $body = $Matches[2]
    $paths = $null
    if ($fm -match "(?m)^\s*paths:\s*(\[.*\])\s*$") {
      try { $paths = @([string[]]($Matches[1] | ConvertFrom-Json)) } catch { $paths = $null }
    }
    return @{ Paths = $paths; Body = $body.TrimEnd() }
  }
  return @{ Paths = $null; Body = $raw.TrimEnd() }
}
# Only emit glob entries over a conservative charset — the value is repo-controlled text landing
# in generated YAML; anything else is dropped rather than risk malformed frontmatter.
function Test-SafeGlob([string]$g) { $g -match "^[A-Za-z0-9_./*?{}\[\]-]+$" }

# Read text as UTF-8 EXPLICITLY. Windows PowerShell 5.1's default for -Raw is the ANSI codepage, so
# a BOM-less UTF-8 rule file (which all of these are) decodes as Windows-1252 and every em-dash
# becomes "â€"" -- silently baked into every generated file in every repo. pwsh 7 defaults to UTF-8
# and hides the bug, so this only bites when something runs the generator with powershell.exe.
function ReadUtf8([string]$p) { Get-Content -Raw -Encoding UTF8 $p }
# Same story on the way out: 5.1's `Set-Content -Encoding UTF8` writes a BOM, pwsh 7's does not, so
# the same source generated by different runtimes produces byte-different files. Pin it to UTF-8
# without BOM in both.
function WriteUtf8([string]$p, [string]$text) {
  [System.IO.File]::WriteAllText($p, $text, (New-Object System.Text.UTF8Encoding($false)))
}

$alwaysBodies = @()      # concatenated into the always-loaded Claude rules block
$allBodies    = @()      # everything, in file order (AGENTS.md + Cursor)
$scopedClaude = @()      # @{ Name; Paths; Body } -> separate path-scoped Claude rule files
foreach ($rf in $ruleFiles) {
  $parsed = Split-RuleFrontmatter ((ReadUtf8 $rf.FullName).TrimEnd())
  $allBodies += $parsed.Body
  $safePaths = if ($parsed.Paths) { @($parsed.Paths | Where-Object { Test-SafeGlob $_ }) } else { @() }
  if ($safePaths.Count -gt 0) {
    $scopedClaude += @{ Name = $rf.BaseName; Paths = $safePaths; Body = $parsed.Body }
  } else {
    $alwaysBodies += $parsed.Body
  }
}
$rulesBody = ($alwaysBodies -join "`n`n")   # Claude always-loaded block
$fullBody  = ($allBodies -join "`n`n")      # AGENTS.md + Cursor (everything, in file order)

$board = $null
$boardPath = Join-Path $agentsDir "board.json"
if (Test-Path $boardPath) { $board = ReadUtf8 $boardPath | ConvertFrom-Json }
$repoSlug = if ($board -and $board.repo) { $board.repo } else { Split-Path -Leaf $repoRoot }

function Sha([string]$text) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))) -replace '-','').ToLowerInvariant() }
  finally { $sha.Dispose() }
}
# Normalize to LF so checksums are stable regardless of how git/editors handle EOL.
function Norm([string]$s) { ($s -replace "`r`n","`n").TrimEnd() + "`n" }
# PSCustomObject (from ConvertFrom-Json) -> mutable hashtable tree, for safe JSON merging.
function ToHt($o) {
  if ($o -is [System.Management.Automation.PSCustomObject]) {
    $h = @{}; foreach ($p in $o.PSObject.Properties) { $h[$p.Name] = ToHt $p.Value }; return $h
  } elseif ($o -is [System.Collections.IEnumerable] -and $o -isnot [string]) {
    # `,` keeps this an array on the way out. Without it PowerShell unrolls a ONE-element result to
    # the bare element, so a merge pass silently rewrote `"args": ["x"]` as `"args": "x"` -- damaging
    # every single-arg MCP server entry (and any 1-item hook list) in the repo's config on each regen.
    return ,@($o | ForEach-Object { ToHt $_ })
  } else { return $o }
}

# --- build outputs (content keyed by repo-relative path) ---------------------------------
$outputs = [ordered]@{}

# AGENTS.md + Cursor include EVERYTHING (they have no per-file lazy-load), so use $fullBody.
$outputs["AGENTS.md"] = Norm @"
<!-- $WARN -->
# Agent guide — repo: $repoSlug

$fullBody
"@

if ($cursorEnabled) {
  $outputs[".cursor/rules/00-akira-agents.mdc"] = Norm @"
---
description: Akira agent rules (repo: $repoSlug)
alwaysApply: true
---
<!-- $WARN -->

$fullBody
"@
}

# Claude Code auto-loads `.claude/rules/**/*.md` (NOT AGENTS.md, NOT .claude/CLAUDE.agents.md).
# So the board rules MUST live here to actually reach a Claude session. This file holds only the
# ALWAYS-loaded rules ($rulesBody); frontmatter-tagged sources go to path-scoped siblings below.
$outputs[".claude/rules/akira-agents.md"] = Norm @"
<!-- $WARN -->
# Agent rules (repo: $repoSlug)

$rulesBody
"@

# Path-scoped Claude rule files — one per frontmatter-tagged source. Claude loads each only when
# working under a matching path, so large situational guidance stays out of always-on context.
foreach ($sc in $scopedClaude) {
  $safeName  = ($sc.Name -replace '[^A-Za-z0-9._-]', '-')
  $pathsYaml = (($sc.Paths | ForEach-Object { "  - `"$_`"" }) -join "`n")
  $outputs[".claude/rules/akira-$safeName.md"] = Norm @"
---
paths:
$pathsYaml
---
<!-- $WARN -->
# $($sc.Name) (repo: $repoSlug)

$($sc.Body)
"@
}

# Retire the old non-loaded file if a prior generation left it behind.
$staleClaudeAgents = Join-Path $repoRoot ".claude\CLAUDE.agents.md"
if (-not $Check -and (Test-Path $staleClaudeAgents)) { Remove-Item $staleClaudeAgents -Force -ErrorAction SilentlyContinue }

# Retire path-scoped rule files from a previous generation whose source lost its frontmatter (or
# was removed) — keep only the akira-*.md files we're emitting now, so stale scoped copies don't
# linger and double-load.
if (-not $Check) {
  $claudeRulesDir = Join-Path $repoRoot ".claude\rules"
  if (Test-Path $claudeRulesDir) {
    $keep = @($outputs.Keys | Where-Object { $_ -like ".claude/rules/*" } | ForEach-Object { Split-Path -Leaf $_ })
    Get-ChildItem $claudeRulesDir -Filter "akira-*.md" | Where-Object { $keep -notcontains $_.Name } |
      ForEach-Object { Remove-Item $_.FullName -Force -ErrorAction SilentlyContinue }
  }
}

# --- retire Cursor artifacts when the lane is off ----------------------------------------
# Surgical, not a wipe: a repo's .cursor/ may hold the operator's own config, so remove ONLY the
# file we generated and ONLY our mcpServers key, then drop now-empty dirs/files we created.
if (-not $Check -and -not $cursorEnabled) {
  $cursorDir = Join-Path $repoRoot ".cursor"
  $mdc = Join-Path $cursorDir "rules\00-akira-agents.mdc"
  if (Test-Path $mdc) {
    Remove-Item $mdc -Force -ErrorAction SilentlyContinue
    Write-Host "  retired .cursor/rules/00-akira-agents.mdc (Cursor lane off)" -ForegroundColor DarkGray
  }
  $cursorMcp = Join-Path $cursorDir "mcp.json"
  if (Test-Path $cursorMcp) {
    try {
      $cm = ToHt (ReadUtf8 $cursorMcp | ConvertFrom-Json)
      if ($cm.ContainsKey('mcpServers') -and $cm['mcpServers'].ContainsKey('hermes-board')) {
        $cm['mcpServers'].Remove('hermes-board')
        # Only OUR server and nothing else left -> the file exists solely because we made it.
        if ($cm['mcpServers'].Count -eq 0 -and $cm.Count -eq 1) {
          Remove-Item $cursorMcp -Force -ErrorAction SilentlyContinue
        } else {
          WriteUtf8 $cursorMcp (($cm | ConvertTo-Json -Depth 12) + [Environment]::NewLine)
        }
        Write-Host "  retired hermes-board MCP entry from .cursor/mcp.json" -ForegroundColor DarkGray
      }
    } catch { }   # hand-edited/malformed: leave it alone rather than damage operator config
  }
  foreach ($d in @((Join-Path $cursorDir "rules"), $cursorDir)) {
    if ((Test-Path $d) -and -not (Get-ChildItem $d -Force)) { Remove-Item $d -Force -ErrorAction SilentlyContinue }
  }
}

# --- write / check helpers ---------------------------------------------------------------
$lock = if ((Test-Path $lockPath) -and -not $Check) { ReadUtf8 $lockPath | ConvertFrom-Json } else { $null }
$drift = @()

function Emit([string]$rel, [string]$content) {
  $abs = Join-Path $repoRoot ($rel -replace '/','\')
  $want = Sha $content
  if ($Check) {
    $have = if (Test-Path $abs) { Sha (Norm (ReadUtf8 $abs)) } else { "<missing>" }
    if ($have -ne $want) { $script:drift += $rel }
    return @{ path = $rel; sha = $want }
  }
  $dir = Split-Path -Parent $abs
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  WriteUtf8 $abs $content
  Write-Host "  wrote $rel" -ForegroundColor DarkGray
  return @{ path = $rel; sha = $want }
}

# --- emit the simple generated files -----------------------------------------------------
$lockEntries = @()
foreach ($rel in $outputs.Keys) { $lockEntries += Emit $rel $outputs[$rel] }

# --- merge our managed Claude hooks (board-hook) into settings.json (preserve everything else) ---
# Three events: SessionStart (sync + presence register), PostToolUse (presence heartbeat + file
# touched), Stop (clear presence). Adaptive command: repo-relative if this repo ships
# board-hook.ps1, else the `akira-board-hook` PATH shim. Not checksummed (repo may add hooks).
$settingsRel = ".claude/settings.json"
$settingsAbs = Join-Path $repoRoot ".claude\settings.json"
$localHook = Join-Path $repoRoot "scripts\agents\board-hook.ps1"
function HookCmd([string]$e) {
  if (Test-Path $localHook) { "pwsh -NoProfile -File `"`$CLAUDE_PROJECT_DIR/scripts/agents/board-hook.ps1`" -Event $e" }
  else { "akira-board-hook $e" }
}
$managed = [ordered]@{
  SessionStart = @{ hooks = @(@{ type='command'; command=(HookCmd 'SessionStart') }) }
  PreToolUse   = @{ matcher='Edit|Write|MultiEdit|NotebookEdit'; hooks = @(@{ type='command'; command=(HookCmd 'PreToolUse') }) }
  PostToolUse  = @{ matcher='Edit|Write|MultiEdit|NotebookEdit'; hooks = @(@{ type='command'; command=(HookCmd 'PostToolUse') }) }
  Stop         = @{ hooks = @(@{ type='command'; command=(HookCmd 'Stop') }) }
}
$ownRe  = 'board-hook'              # commands we currently own
$dropRe  = 'board-hook|akira-board' # on regen, drop ours + any legacy `akira-board sync` hook

if ($Check) {
  $present = $true
  $j = if (Test-Path $settingsAbs) { ReadUtf8 $settingsAbs | ConvertFrom-Json } else { $null }
  foreach ($evt in $managed.Keys) {
    $groups = if ($j) { $j.hooks.$evt } else { $null }
    $has = $groups -and (@($groups | Where-Object { $_.hooks | Where-Object { $_.command -match $ownRe } }).Count -gt 0)
    if (-not $has) { $present = $false }
  }
  if (-not $present) { $drift += "$settingsRel (board hooks missing/stale)" }
} else {
  $settings = if (Test-Path $settingsAbs) { ReadUtf8 $settingsAbs | ConvertFrom-Json } else { [pscustomobject]@{} }
  $s = ToHt $settings
  if (-not $s.ContainsKey('hooks')) { $s['hooks'] = @{} }
  foreach ($evt in $managed.Keys) {
    if (-not $s['hooks'].ContainsKey($evt)) { $s['hooks'][$evt] = @() }
    $kept = @($s['hooks'][$evt] | Where-Object { -not ($_.hooks | Where-Object { $_.command -match $dropRe }) })
    $s['hooks'][$evt] = @($kept + $managed[$evt])
  }
  $dir = Split-Path -Parent $settingsAbs
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  WriteUtf8 $settingsAbs (($s | ConvertTo-Json -Depth 12) + [Environment]::NewLine)
  Write-Host "  merged board hooks (SessionStart/PostToolUse/Stop) -> $settingsRel" -ForegroundColor DarkGray
}

# --- mount the Hermes Kanban MCP server (kanban_* tools) into Claude + Cursor --------------
# Merge-aware (preserve other servers). Command = the `akira-mcp-board` PATH shim, so no akira
# path or secret lands in the committed repo config. Not checksummed (repo may add servers).
# grc-chat rides the SAME shim mechanism for the same reason. akira's own .mcp.json named the
# relative path "tools/claude-shim/mcp-grc-host.mjs", which resolves only inside akira — so every
# other repo's agents had no GRC tools, making cross-repo coordination on a shared card impossible
# in precisely the repos that needed it. A PATH shim resolves from any working directory and keeps
# akira's absolute path out of the committed config.
$mcpServers = [ordered]@{
  "hermes-board" = @{ command = "akira-mcp-board"; args = @() }
  "grc-chat"     = @{ command = "akira-mcp-grc";   args = @() }
}
$mcpTargets = [ordered]@{
  ".mcp.json"        = (Join-Path $repoRoot ".mcp.json")
}
if ($cursorEnabled) { $mcpTargets[".cursor/mcp.json"] = (Join-Path $repoRoot ".cursor\mcp.json") }
foreach ($rel in $mcpTargets.Keys) {
  $abs = $mcpTargets[$rel]
  if ($Check) {
    foreach ($mcpName in $mcpServers.Keys) {
      $present = $false
      if (Test-Path $abs) { try { $present = $null -ne (ReadUtf8 $abs | ConvertFrom-Json).mcpServers.$mcpName } catch {} }
      if (-not $present) { $drift += "$rel ($mcpName MCP server missing)" }
    }
  } else {
    $j = if (Test-Path $abs) { ReadUtf8 $abs | ConvertFrom-Json } else { [pscustomobject]@{} }
    $m = ToHt $j
    if (-not $m.ContainsKey('mcpServers')) { $m['mcpServers'] = @{} }
    foreach ($mcpName in $mcpServers.Keys) {
      # Never clobber a repo that deliberately points grc-chat somewhere else (e.g. akira itself,
      # which can run the module directly). Only ADD what is missing.
      if (-not $m['mcpServers'].ContainsKey($mcpName)) { $m['mcpServers'][$mcpName] = $mcpServers[$mcpName] }
    }
    $dir = Split-Path -Parent $abs
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    WriteUtf8 $abs (($m | ConvertTo-Json -Depth 12) + [Environment]::NewLine)
    Write-Host "  mounted MCP servers -> $rel" -ForegroundColor DarkGray
  }
}

# --- ensure .agents is git-ignored in this repo ------------------------------------------
# .agents/ is generated/synced tooling (copied from the akira template + regenerated), not repo
# content — keep it out of the host repo's git history so syncs don't create committable noise.
if (-not $Check) {
  $giPath = Join-Path $repoRoot ".gitignore"
  $giLines = if (Test-Path $giPath) { @(Get-Content $giPath) } else { @() }
  if (($giLines | ForEach-Object { $_.Trim().TrimEnd('/') }) -notcontains '.agents') {
    Add-Content -Path $giPath -Value "`n# Akira agent-config source (generated/synced - not repo content)`n.agents/" -Encoding UTF8
    Write-Host "  git-ignored .agents/ -> .gitignore" -ForegroundColor DarkGray
  }
}

# --- lock / report -----------------------------------------------------------------------
if ($Check) {
  if ($drift) {
    Write-Host "DRIFT — these generated files are stale or hand-edited:" -ForegroundColor Red
    $drift | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host "Run: pwsh -File .agents/generate.ps1" -ForegroundColor Yellow
    exit 1
  }
  Write-Host "OK — generated files match .agents/ source." -ForegroundColor Green
  exit 0
}

WriteUtf8 $lockPath ((@{ generatedFrom = "repo:$repoSlug"; files = $lockEntries } | ConvertTo-Json -Depth 6) + [Environment]::NewLine)
Write-Host "Generated agent config for repo '$repoSlug'. Lock written to .agents/agents.lock." -ForegroundColor Green
