#requires -Version 5.1
<#
.SYNOPSIS
  Generate per-runtime agent config (.claude, .cursor, AGENTS.md) from .agents/ — the single
  source of truth. Run after editing anything under .agents/. Idempotent.

.DESCRIPTION
  .agents/ holds the canonical rules + board identity for this repo. Each agent runtime wants
  the same rules in its own format; hand-syncing N directories drifts. So we GENERATE them:

    .agents/rules/*.md  +  .agents/board.json
        │
        ├─> AGENTS.md                          (cross-tool standard: Cursor, others read it)
        ├─> .cursor/rules/00-akira-agents.mdc  (Cursor, alwaysApply)
        ├─> .claude/CLAUDE.agents.md           (rules block Claude reads)
        └─> .claude/settings.json              (merge a SessionStart hook: `akira-board sync`)

  Generated files carry a "DO NOT EDIT" header and are checksummed into .agents/agents.lock.

.PARAMETER Check
  Don't write — verify generated outputs still match the lock (CI / pre-commit). Exits 1 on
  drift (a generated file was hand-edited or is stale), 0 if clean.
#>
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = "Stop"
$agentsDir = $PSScriptRoot
$repoRoot  = Split-Path -Parent $agentsDir
$rulesDir  = Join-Path $agentsDir "rules"
$lockPath  = Join-Path $agentsDir "agents.lock"
$marker    = "akira-board"        # identifies OUR managed Claude hook (substring of BOTH the repo-relative and PATH-shim $hookCmd forms)

$WARN = "GENERATED by .agents/generate.ps1 from .agents/ — DO NOT EDIT. Edit .agents/rules/*.md and re-run."

# --- gather source -----------------------------------------------------------------------
if (-not (Test-Path $rulesDir)) { throw "No .agents/rules dir at $rulesDir" }
$ruleFiles = Get-ChildItem $rulesDir -Filter *.md | Sort-Object Name
if (-not $ruleFiles) { throw "No rule files in $rulesDir" }
$rulesBody = ($ruleFiles | ForEach-Object { (Get-Content -Raw $_.FullName).TrimEnd() }) -join "`n`n"

$board = $null
$boardPath = Join-Path $agentsDir "board.json"
if (Test-Path $boardPath) { $board = Get-Content -Raw $boardPath | ConvertFrom-Json }
$repoSlug = if ($board -and $board.repo) { $board.repo } else { Split-Path -Leaf $repoRoot }

function Sha([string]$text) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  try { ([BitConverter]::ToString($sha.ComputeHash([Text.Encoding]::UTF8.GetBytes($text))) -replace '-','').ToLowerInvariant() }
  finally { $sha.Dispose() }
}
# Normalize to LF so checksums are stable regardless of how git/editors handle EOL.
function Norm([string]$s) { ($s -replace "`r`n","`n").TrimEnd() + "`n" }
# PSCustomObject (from ConvertFrom-Json) -> mutable hashtable tree, for safe JSON merging.
function ToHt($o) {
  if ($o -is [System.Management.Automation.PSCustomObject]) {
    $h = @{}; foreach ($p in $o.PSObject.Properties) { $h[$p.Name] = ToHt $p.Value }; return $h
  } elseif ($o -is [System.Collections.IEnumerable] -and $o -isnot [string]) {
    return @($o | ForEach-Object { ToHt $_ })
  } else { return $o }
}

# --- build outputs (content keyed by repo-relative path) ---------------------------------
$outputs = [ordered]@{}

$outputs["AGENTS.md"] = Norm @"
<!-- $WARN -->
# Agent guide — repo: $repoSlug

$rulesBody
"@

$outputs[".cursor/rules/00-akira-agents.mdc"] = Norm @"
---
description: Akira agent rules (repo: $repoSlug)
alwaysApply: true
---
<!-- $WARN -->

$rulesBody
"@

# Claude Code auto-loads `.claude/rules/**/*.md` (NOT AGENTS.md, NOT .claude/CLAUDE.agents.md).
# So the board rules MUST live here to actually reach a Claude session.
$outputs[".claude/rules/akira-agents.md"] = Norm @"
<!-- $WARN -->
# Agent rules (repo: $repoSlug)

$rulesBody
"@

# Retire the old non-loaded file if a prior generation left it behind.
$staleClaudeAgents = Join-Path $repoRoot ".claude\CLAUDE.agents.md"
if (-not $Check -and (Test-Path $staleClaudeAgents)) { Remove-Item $staleClaudeAgents -Force -ErrorAction SilentlyContinue }

# --- write / check helpers ---------------------------------------------------------------
$lock = if ((Test-Path $lockPath) -and -not $Check) { Get-Content -Raw $lockPath | ConvertFrom-Json } else { $null }
$drift = @()

function Emit([string]$rel, [string]$content) {
  $abs = Join-Path $repoRoot ($rel -replace '/','\')
  $want = Sha $content
  if ($Check) {
    $have = if (Test-Path $abs) { Sha (Norm (Get-Content -Raw $abs)) } else { "<missing>" }
    if ($have -ne $want) { $script:drift += $rel }
    return @{ path = $rel; sha = $want }
  }
  $dir = Split-Path -Parent $abs
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  Set-Content -Path $abs -Value $content -NoNewline -Encoding UTF8
  Write-Host "  wrote $rel" -ForegroundColor DarkGray
  return @{ path = $rel; sha = $want }
}

# --- emit the simple generated files -----------------------------------------------------
$lockEntries = @()
foreach ($rel in $outputs.Keys) { $lockEntries += Emit $rel $outputs[$rel] }

# --- merge our managed Claude hooks (board-hook) into settings.json (preserve everything else) ---
# Three events: SessionStart (sync + presence register), PostToolUse (presence heartbeat + file
# touched), Stop (clear presence). Adaptive command: repo-relative if this repo ships
# board-hook.ps1, else the `akira-board-hook` PATH shim. Not checksummed (repo may add hooks).
$settingsRel = ".claude/settings.json"
$settingsAbs = Join-Path $repoRoot ".claude\settings.json"
$localHook = Join-Path $repoRoot "scripts\agents\board-hook.ps1"
function HookCmd([string]$e) {
  if (Test-Path $localHook) { "pwsh -NoProfile -File `"`$CLAUDE_PROJECT_DIR/scripts/agents/board-hook.ps1`" -Event $e" }
  else { "akira-board-hook $e" }
}
$managed = [ordered]@{
  SessionStart = @{ hooks = @(@{ type='command'; command=(HookCmd 'SessionStart') }) }
  PreToolUse   = @{ matcher='Edit|Write|MultiEdit|NotebookEdit'; hooks = @(@{ type='command'; command=(HookCmd 'PreToolUse') }) }
  PostToolUse  = @{ matcher='Edit|Write|MultiEdit|NotebookEdit'; hooks = @(@{ type='command'; command=(HookCmd 'PostToolUse') }) }
  Stop         = @{ hooks = @(@{ type='command'; command=(HookCmd 'Stop') }) }
}
$ownRe  = 'board-hook'              # commands we currently own
$dropRe  = 'board-hook|akira-board' # on regen, drop ours + any legacy `akira-board sync` hook

if ($Check) {
  $present = $true
  $j = if (Test-Path $settingsAbs) { Get-Content -Raw $settingsAbs | ConvertFrom-Json } else { $null }
  foreach ($evt in $managed.Keys) {
    $groups = if ($j) { $j.hooks.$evt } else { $null }
    $has = $groups -and (@($groups | Where-Object { $_.hooks | Where-Object { $_.command -match $ownRe } }).Count -gt 0)
    if (-not $has) { $present = $false }
  }
  if (-not $present) { $drift += "$settingsRel (board hooks missing/stale)" }
} else {
  $settings = if (Test-Path $settingsAbs) { Get-Content -Raw $settingsAbs | ConvertFrom-Json } else { [pscustomobject]@{} }
  $s = ToHt $settings
  if (-not $s.ContainsKey('hooks')) { $s['hooks'] = @{} }
  foreach ($evt in $managed.Keys) {
    if (-not $s['hooks'].ContainsKey($evt)) { $s['hooks'][$evt] = @() }
    $kept = @($s['hooks'][$evt] | Where-Object { -not ($_.hooks | Where-Object { $_.command -match $dropRe }) })
    $s['hooks'][$evt] = @($kept + $managed[$evt])
  }
  $dir = Split-Path -Parent $settingsAbs
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  ($s | ConvertTo-Json -Depth 12) | Set-Content -Path $settingsAbs -Encoding UTF8
  Write-Host "  merged board hooks (SessionStart/PostToolUse/Stop) -> $settingsRel" -ForegroundColor DarkGray
}

# --- mount the Hermes Kanban MCP server (kanban_* tools) into Claude + Cursor --------------
# Merge-aware (preserve other servers). Command = the `akira-mcp-board` PATH shim, so no akira
# path or secret lands in the committed repo config. Not checksummed (repo may add servers).
$mcpName = "hermes-board"
$mcpEntry = @{ command = "akira-mcp-board"; args = @() }
$mcpTargets = [ordered]@{
  ".mcp.json"        = (Join-Path $repoRoot ".mcp.json")
  ".cursor/mcp.json" = (Join-Path $repoRoot ".cursor\mcp.json")
}
foreach ($rel in $mcpTargets.Keys) {
  $abs = $mcpTargets[$rel]
  if ($Check) {
    $present = $false
    if (Test-Path $abs) { try { $present = $null -ne (Get-Content -Raw $abs | ConvertFrom-Json).mcpServers.$mcpName } catch {} }
    if (-not $present) { $drift += "$rel ($mcpName MCP server missing)" }
  } else {
    $j = if (Test-Path $abs) { Get-Content -Raw $abs | ConvertFrom-Json } else { [pscustomobject]@{} }
    $m = ToHt $j
    if (-not $m.ContainsKey('mcpServers')) { $m['mcpServers'] = @{} }
    $m['mcpServers'][$mcpName] = $mcpEntry
    $dir = Split-Path -Parent $abs
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
    ($m | ConvertTo-Json -Depth 12) | Set-Content -Path $abs -Encoding UTF8
    Write-Host "  mounted MCP server -> $rel" -ForegroundColor DarkGray
  }
}

# --- lock / report -----------------------------------------------------------------------
if ($Check) {
  if ($drift) {
    Write-Host "DRIFT — these generated files are stale or hand-edited:" -ForegroundColor Red
    $drift | ForEach-Object { Write-Host "  - $_" -ForegroundColor Red }
    Write-Host "Run: pwsh -File .agents/generate.ps1" -ForegroundColor Yellow
    exit 1
  }
  Write-Host "OK — generated files match .agents/ source." -ForegroundColor Green
  exit 0
}

@{ generatedFrom = "repo:$repoSlug"; files = $lockEntries } | ConvertTo-Json -Depth 6 |
  Set-Content -Path $lockPath -Encoding UTF8
Write-Host "Generated agent config for repo '$repoSlug'. Lock written to .agents/agents.lock." -ForegroundColor Green
